### ISSUE TITLE
Incompatibilidade com Magento 2.4.5-p3 ou menor

### ISSUE THREAD

**Issue by chavesfop** [pagaleve/pagaleve-magento2-extension#4]
De acordo com a descrição do modulo temos que:
```
This plugin supports: PHP 7.3.0 version and higher. Magento2 version 2.3.3 and higher.
```
Porém, depois da release 1.4.0 o modulo esta compativel APENAS com a versão 2.4.6 ou superior, a classe `Magento\Framework\HTTP\LaminasClientFactory` foi implantada no Magento\Framework a partir da versão 2.4.6.  
Em versões inferiores a 2.4.6 ocorre um erro ao executar o comando `bin/magento s:di:compile`, para realizar a instalação no Magento 2.4.5-p3 utilizei a release 1.3.0 deste modulo.

**Comment by warleyelias** [comment]
@chavesfop realmente, a versão 1.4.0 em diante será compativel apenas com Magento 2.4.6 em diante, favor utilizar a versão 1.3.0, essa é compativel com magento 2.4.5.
Vamos atualizar a descrição do mesmo.
